Services/Recruiting/RecruitingWeb/Models/ErrorViewModel.cs
namespace RecruitingWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Services/Recruiting/RecruitingWeb/Controllers/CandidateController.cs
using Microsoft.AspNetCore.Mvc;

namespace RecruitingWeb.Controllers
{
    public class CandidateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Services/Recruiting/RecruitingWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RecruitingWeb.Models;
using System.Diagnostics;

namespace RecruitingWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Jobs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Services/Recruiting/RecruitingWeb/Controllers/JobsController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using ApplicationCore.Models;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace RecruitingWeb.Controllers
{
    public class JobsController : Controller
    {
        private IJobService _jobService;

        public JobsController(IJobService jobService)
        {
            _jobService = jobService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // ASP.NET will assign a thread from thread pool to do this task
            // IO bound 2 sec, 10 ms, 10 sec, 300ms
            // network, locatio, database disk SSD, hard drive, SQL fast or slow, might not be optimized
            var jobs = await _jobService.GetAllJobs();
            // return all the jobs so that candidates can apply to the job
            return View(jobs);
        }

        [HttpGet]
        // get the job detail information
        public async Task<IActionResult> Details(int id)
        {
            var job = await _jobService.GetJobById(id);
            return View(job);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // dropdown of job status
            List<JobStatusLookUp> sl = new List<JobStatusLookUp>();
            sl = await _jobService.GetJobStatus();
            ViewBag.message = sl;
            // take the information from view and save to DB
            return View();
        }

        // Saving job information
        [HttpPost]
        public async Task<IActionResult> Create(JobRequestModel model)
        {
            // check if model is valid, on server
            if(!ModelState.IsValid)
            {
                return View();
            }

            // save data in database
            await _jobService.AddJob(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetJobsByDepartment(int id, int pageSize = 30, int pageNumber = 1)
        {
            var job = await _jobService.GetJobsByDepartment(id, pageSize, pageNumber);
            return View();
        }
    }
}

Services/Recruiting/RecruitingWeb/Controllers/StatusController.cs
namespace RecruitingWeb.Controllers
{
    public class StatusController
    {
    }
}

Services/Recruiting/RecruitingWeb/Controllers/SubmissionsController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Entities;
using ApplicationCore.Models;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace RecruitingWeb.Controllers
{
    public class SubmissionsController : Controller
    {
        private ISubmissionService _submissionService;

        public SubmissionsController(ISubmissionService submissionService)
        {
            _submissionService = submissionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var subs = await _submissionService.GetAllSubmissions();
            return View(subs);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int jobId)
        {
            var sub = new SubmissionRequestModel { Id = jobId, JobId = jobId};
            return View(sub);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int jobId, SubmissionRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await _submissionService.AddSubmission(model);
            return RedirectToAction("Index");
        }
    }
}

Services/Recruiting/RecruitingWeb/Views/Home/Jobs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>
    This is Jobs View.
</h1>

Services/Recruiting/RecruitingWeb/Views/Jobs/Create.cshtml
@model ApplicationCore.Models.JobRequestModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>JobRequestModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPositions" class="control-label"></label>
                <input asp-for="NumberOfPositions" class="form-control" />
                <span asp-validation-for="NumberOfPositions" class="text-danger"></span>
            </div>
            <div>
                <select asp-for="Id" asp-items="@(new SelectList(ViewBag.message,"Id","JobStatusCode"))"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Services/Recruiting/RecruitingWeb/Views/Jobs/Details.cshtml
@model ApplicationCore.Models.JobResponseModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>JobResponseModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfPositions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfPositions)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Services/Recruiting/RecruitingWeb/Views/Jobs/Index.cshtml
@model IEnumerable<ApplicationCore.Models.JobResponseModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfPositions)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                    <a asp-controller="Jobs" asp-action="Details" asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Title)
                        </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfPositions)
            </td>
            
        </tr>
}
    </tbody>
</table>

Services/Recruiting/RecruitingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecruitingWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecruitingWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RecruitingWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RecruitingWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Services/Recruiting/RecruitingWeb/Views/Submissions/Create.cshtml
@model ApplicationCore.Models.SubmissionRequestModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SubmissionRequestModel Job Id: @Model.JobId</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Services/Recruiting/RecruitingWeb/Views/Submissions/Index.cshtml
@model IEnumerable<ApplicationCore.Models.SubmissionResponseModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CandidateId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CandidateId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>

        </tr>
}
    </tbody>
</table>